# Generated by Django 5.1.2 on 2024-11-23 13:39

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[account.validators.validate_email_domain], verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[account.validators.validate_iranian_mobile_number], verbose_name='شماره موبایل'),
        ),
    ]
