# Generated by Django 5.1.2 on 2024-11-22 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_groupmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmanager',
            options={'verbose_name': 'مدیر گروه', 'verbose_name_plural': 'لیست مدیر گروه ها'},
        ),
        migrations.AlterUniqueTogether(
            name='groupmanager',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='group',
            name='field_of_study',
            field=models.CharField(max_length=100, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام گروه'),
        ),
        migrations.AlterField(
            model_name='groupmanager',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='account.group', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='groupmanager',
            name='name',
            field=models.CharField(max_length=150, verbose_name='نام مدیر گروه'),
        ),
        migrations.AlterField(
            model_name='groupmanager',
            name='national_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='کدملی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lessons_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_group', to='account.group', verbose_name='گروه'),
        ),
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('دکتری', 'Ph.D.'), ('ارشد', 'Master')], max_length=50, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ترم جاری', 'Current'), ('دفاع شده', 'Defended')], max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='شماره دانشجویی'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام استاد')),
                ('national_code', models.CharField(max_length=10, unique=True, verbose_name='کدملی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'لیست اساتید',
            },
        ),
    ]
